"""Initial migration.

Revision ID: 5b1c3b32bf22
Revises: 
Create Date: 2024-08-03 12:45:27.530008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1c3b32bf22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('Outreach')
    op.drop_table('Certifications')
    op.drop_table('Quotation')
    op.drop_table('SeminarEventOthers')
    op.drop_table('Project Progress')
    op.drop_table('POs')
    op.drop_table('Visitor Data')
    op.drop_table('prospects')
    op.drop_table('Invoice Raised')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Invoice Raised',
    sa.Column('S.No', sa.INTEGER(), nullable=True),
    sa.Column('Invoice No', sa.TEXT(), nullable=True),
    sa.Column('Invoice date', sa.TIMESTAMP(), nullable=True),
    sa.Column('Vendor Name', sa.TEXT(), nullable=True),
    sa.Column('Type of Work', sa.TEXT(), nullable=True),
    sa.Column('MSME/ Start-Up/ Institution', sa.TEXT(), nullable=True),
    sa.Column('Total Service Value', sa.TEXT(), nullable=True),
    sa.Column('CGST 9%', sa.REAL(), nullable=True),
    sa.Column('SGST 9%', sa.REAL(), nullable=True),
    sa.Column('Total TAX Invoice', sa.REAL(), nullable=True),
    sa.Column('Amount Received', sa.REAL(), nullable=True),
    sa.Column('Payment Received date', sa.TEXT(), nullable=True),
    sa.Column('Remarks', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('S.No')
    )
    op.create_table('prospects',
    sa.Column('Lead Owner', sa.TEXT(), nullable=True),
    sa.Column('Client Name', sa.TEXT(), nullable=True),
    sa.Column('Client Type ', sa.TEXT(), nullable=True),
    sa.Column('Client requirement', sa.TEXT(), nullable=True),
    sa.Column('Tentative revenue\n (approx)', sa.TEXT(), nullable=True),
    sa.Column('Status (Hot-Warm-Cold)', sa.TEXT(), nullable=True),
    sa.Column('Last Follow \n Up date', sa.TEXT(), nullable=True),
    sa.Column('Last Remarks', sa.TEXT(), nullable=True),
    sa.Column('Next Follow Up Date', sa.TEXT(), nullable=True),
    sa.Column('Lab', sa.TEXT(), nullable=True),
    sa.Column('Project Manager', sa.TEXT(), nullable=True),
    sa.Column('Time Duration', sa.TEXT(), nullable=True),
    sa.Column('Date of Lead', sa.TEXT(), nullable=True),
    sa.Column('Email address', sa.TEXT(), nullable=True),
    sa.Column('Phone Number', sa.TEXT(), nullable=True),
    sa.Column('Unnamed: 15', sa.TEXT(), nullable=True)
    )
    op.create_table('Visitor Data',
    sa.Column('Date', sa.TEXT(), nullable=True),
    sa.Column('Client Type', sa.TEXT(), nullable=True),
    sa.Column('Visitor Name', sa.TEXT(), nullable=True),
    sa.Column('Organization Name', sa.TEXT(), nullable=True),
    sa.Column(' To Meet Whom', sa.TEXT(), nullable=True),
    sa.Column('Purpose of the Meeting', sa.TEXT(), nullable=True),
    sa.Column('Phone number', sa.REAL(), nullable=True),
    sa.Column('Visiting Card ( Y/ N)', sa.TEXT(), nullable=True),
    sa.Column('E-mail address', sa.TEXT(), nullable=True),
    sa.Column('Website', sa.TEXT(), nullable=True),
    sa.Column('Chennai city/Tamil nadu (other cities) /Other states/International', sa.TEXT(), nullable=True),
    sa.Column('Prospect (Y/N)', sa.TEXT(), nullable=True),
    sa.Column('S.NO', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('S.NO')
    )
    op.create_table('POs',
    sa.Column('Invoice Sno', sa.TEXT(), nullable=True),
    sa.Column('P.O. / Invoice / W.O. No.', sa.TEXT(), nullable=True),
    sa.Column('Date', sa.TIMESTAMP(), nullable=True),
    sa.Column('Client Name', sa.TEXT(), nullable=True),
    sa.Column('Type of Work', sa.TEXT(), nullable=True),
    sa.Column('Description', sa.TEXT(), nullable=True),
    sa.Column('Amount without TAX (In INR)', sa.INTEGER(), nullable=True),
    sa.Column('Amount With Tax (In INR)', sa.INTEGER(), nullable=True),
    sa.Column('Amount Billed', sa.INTEGER(), nullable=True),
    sa.Column('Amount yet to be billed', sa.INTEGER(), nullable=True),
    sa.Column('Amount received incl tax', sa.INTEGER(), nullable=True),
    sa.Column('Amount pending', sa.INTEGER(), nullable=True),
    sa.Column('S.NO', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('S.NO')
    )
    op.create_table('Project Progress',
    sa.Column('Client Name', sa.TEXT(), nullable=True),
    sa.Column('Type of Client', sa.TEXT(), nullable=True),
    sa.Column('Project Description', sa.TEXT(), nullable=True),
    sa.Column('Project Manager', sa.TEXT(), nullable=True),
    sa.Column('Project Team', sa.TEXT(), nullable=True),
    sa.Column('No. of hours', sa.REAL(), nullable=True),
    sa.Column('Date of Starting', sa.TEXT(), nullable=True),
    sa.Column('Date of Ending ', sa.TEXT(), nullable=True),
    sa.Column('Milestones', sa.TEXT(), nullable=True),
    sa.Column('Current Status', sa.TEXT(), nullable=True),
    sa.Column('No. of Hours used', sa.REAL(), nullable=True),
    sa.Column('Unnamed: 11', sa.TEXT(), nullable=True),
    sa.Column('Unnamed: 12', sa.TEXT(), nullable=True),
    sa.Column('S.NO', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('S.NO')
    )
    op.create_table('SeminarEventOthers',
    sa.Column('Type (Seminar/Event/Others)', sa.TEXT(), nullable=True),
    sa.Column('Date', sa.TEXT(), nullable=True),
    sa.Column('Venue', sa.TEXT(), nullable=True),
    sa.Column('No. of Participants', sa.REAL(), nullable=True),
    sa.Column('Event/Seminar Title', sa.TEXT(), nullable=True),
    sa.Column('Purpose', sa.TEXT(), nullable=True),
    sa.Column('Organizer detail', sa.TEXT(), nullable=True),
    sa.Column('Participant Certification (Y/N)', sa.TEXT(), nullable=True),
    sa.Column('S.NO', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('S.NO')
    )
    op.create_table('Quotation',
    sa.Column('Q No', sa.REAL(), nullable=True),
    sa.Column('Date', sa.TEXT(), nullable=True),
    sa.Column('Client Name', sa.TEXT(), nullable=True),
    sa.Column('Client Type', sa.TEXT(), nullable=True),
    sa.Column('Type of Work', sa.TEXT(), nullable=True),
    sa.Column('Work Description', sa.TEXT(), nullable=True),
    sa.Column('Payment Terms', sa.TEXT(), nullable=True),
    sa.Column('Qty', sa.INTEGER(), nullable=True),
    sa.Column('Unit', sa.TEXT(), nullable=True),
    sa.Column('Unit Price', sa.REAL(), nullable=True),
    sa.Column('Base Value', sa.INTEGER(), nullable=True),
    sa.Column('Taxable Value', sa.TEXT(), nullable=True),
    sa.Column('Total Amount', sa.REAL(), nullable=True),
    sa.Column('Discount', sa.REAL(), nullable=True),
    sa.Column('Net Amount', sa.INTEGER(), nullable=True),
    sa.Column('S.NO', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('S.NO')
    )
    op.create_table('Certifications',
    sa.Column('Type of Certification', sa.TEXT(), nullable=True),
    sa.Column('Provided under', sa.TEXT(), nullable=True),
    sa.Column('Beneficiary Name', sa.TEXT(), nullable=True),
    sa.Column('Organization / Institution Name', sa.TEXT(), nullable=True),
    sa.Column('E-mail', sa.TEXT(), nullable=True),
    sa.Column('Contact No', sa.REAL(), nullable=True),
    sa.Column('Program Title', sa.TEXT(), nullable=True),
    sa.Column('Starting Date', sa.TIMESTAMP(), nullable=True),
    sa.Column('End Date', sa.TIMESTAMP(), nullable=True),
    sa.Column('Total no. of hours', sa.TEXT(), nullable=True),
    sa.Column('Trainer details Certified by', sa.TEXT(), nullable=True),
    sa.Column('Revenue', sa.REAL(), nullable=True),
    sa.Column('SIEMENS badge (Y/N)', sa.TEXT(), nullable=True),
    sa.Column('Date of Certification', sa.TIMESTAMP(), nullable=True),
    sa.Column('Certification No', sa.TEXT(), nullable=True),
    sa.Column('S.no', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('S.no')
    )
    op.create_table('Outreach',
    sa.Column('Date', sa.TEXT(), nullable=True),
    sa.Column('Purpose of Outreach', sa.TEXT(), nullable=True),
    sa.Column('Target Audience', sa.TEXT(), nullable=True),
    sa.Column('Type of Outreach', sa.TEXT(), nullable=True),
    sa.Column('TANSAM Representative', sa.TEXT(), nullable=True),
    sa.Column('No. of records/Leads collected', sa.INTEGER(), nullable=True),
    sa.Column('Outreach SPOC details', sa.TEXT(), nullable=True),
    sa.Column('Venue', sa.TEXT(), nullable=True),
    sa.Column('S.no', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('S.no')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
